const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
process.chdir(root);
const pages=require('../src/pages.cjs');
const contact=require('../src/contact.cjs');
const nav=[['/work/','Work'],['/services/','Services'],['/about/','About'],['/hire/','Hire me']];
const link=(url,label,current)=>`<a href="${url}"${current===url?' aria-current="page"':''}>${label}</a>`;
for(const page of pages){
 const url=page.path==='/'?'':page.path;
 const current=page.path.startsWith('/work/')?'/work/':page.path;
 const links=nav.map(([href,label])=>link(href,label,current)).join('');
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title} — Cyrus Alcala</title><meta name="description" content="${page.description}"><link rel="canonical" href="https://cyrusalcala.com${page.path}"><meta property="og:type" content="website"><meta property="og:title" content="${page.title} — Cyrus Alcala"><meta property="og:description" content="${page.description}"><meta property="og:url" content="https://cyrusalcala.com${page.path}"><meta property="og:image" content="https://cyrusalcala.com/assets/social-card.png"><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#f7f3ec"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/site.css"><script src="/site.js" defer></script><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Person',name:'Cyrus Alcala',url:'https://cyrusalcala.com',image:'https://cyrusalcala.com/assets/headshot-dark.webp',sameAs:['https://github.com/cyalcala','https://www.linkedin.com/in/cyrusalcala/'],knowsAbout:['Web design','Technical writing','Knowledge management','AI automation']})}</script></head><body><a class="skip" href="#main">Skip to content</a><header class="masthead wrap"><a class="brand" href="/" aria-label="Cyrus Alcala home">cyrus alcala<span aria-hidden="true" class="accent">.</span><small>INDEPENDENT DIGITAL MAKER · MANILA</small></a><nav class="navlinks" aria-label="Main navigation">${links}<a class="nav-contact" href="${contact.url}">${contact.label} <span aria-hidden="true">↗</span></a></nav><details class="mobile-nav"><summary>Menu <span aria-hidden="true">☰</span></summary><nav aria-label="Mobile navigation">${links}<a href="${contact.url}">${contact.label} ↗</a></nav></details></header><main id="main">${page.body}</main><footer id="contact" class="contact"><div class="wrap"><div class="contact-top"><div><span class="eyebrow label">HAVE SOMETHING IN MIND?</span><h2>Let's make<br>it <span class="serif">happen.</span></h2></div><a class="button" href="${contact.url}">${contact.label} <span aria-hidden="true">↗</span></a></div><div class="contact-bottom"><div>Projects, collaborations or hiring inquiries.<br>Manila, Philippines · Working with you, wherever you are.</div><nav class="footer-links" aria-label="Footer navigation"><a href="https://www.linkedin.com/in/cyrusalcala/">LinkedIn ↗</a><a href="https://github.com/cyalcala">GitHub ↗</a><a href="/hire/">Hire me ↗</a><a href="/assets/Cyrus-Alcala-Resume.docx" download>Résumé ↓</a></nav></div><div class="footer-name" aria-hidden="true">CYRUS ALCALA</div><div class="label muted" style="color:#c7bfb4;margin-top:24px">© 2026 Cyrus Alcala · Thoughtfully made. Always evolving.</div></div></footer></body></html>`;
 const out=page.path==='/'?'build/index.html':`build${page.path}index.html`;
 fs.mkdirSync(path.dirname(out),{recursive:true});fs.writeFileSync(out,html);
}
fs.writeFileSync('build/site.css',fs.readFileSync('src/fonts.css','utf8')+'\n'+fs.readFileSync('src/site.css','utf8'));
fs.copyFileSync('src/site.js','build/site.js');
fs.writeFileSync('build/robots.txt','User-agent: *\nAllow: /\nSitemap: https://cyrusalcala.com/sitemap.xml\n');
fs.writeFileSync('build/sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+pages.filter(p=>p.path!='/404/').map(p=>`<url><loc>https://cyrusalcala.com${p.path}</loc></url>`).join('')+'</urlset>');
fs.writeFileSync('build/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="8" fill="#f7f3ec"/><text x="12" y="48" font-family="Georgia" font-size="55" fill="#1c1917">c</text><circle cx="50" cy="46" r="5" fill="#3f43ea"/></svg>');
fs.writeFileSync('build/_headers','/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: SAMEORIGIN\n/assets/*\n  Cache-Control: public, max-age=86400\n');
fs.copyFileSync('build/404/index.html','build/404.html');
console.log(`Built ${pages.length} static pages with shared assets.`);
